### ISSUE TITLE
Is it possible to support The Ring Method

### ISSUE THREAD

**Issue by SabreRunner** [MrXofar/roll-new-character-stats#2]
Explained here: https://www.youtube.com/watch?v=dxZ9Mk_FdNc

**Comment by MrXofar** [comment]
I like this idea - and it is possible. Let me fiddle with a bit and see what I can come up with.
Off the top of my head, I could see the d6 results being moved around the current Results Zone - instead of the totals as it shows now.

![image](https://user-images.githubusercontent.com/103948142/180631144-639acdb4-e80b-4e28-a6c6-edcfcb629439.png)

**Comment by SabreRunner** [comment]
If there could be an option to have X d6s rolled, scrollable on the results line, and being able to choose Y of them to add to Z attribute, that would be great.

**Comment by MrXofar** [comment]
I suspect the "ring" aspect is so the first and last rolls can be selected together. So, an infinite x scroll <-- -->, click three consecutive to select, and drag the group to the ability might do the trick. Would save a lot of real estate too.

The only draw-back I can see to the system is if a player wants to reset just one ability and get those rolls back to move somewhere else or combine with other remaining rolls. A solution to that might be to just allow full reset so they have to start over with their results, and/or once they comit to a total, the best they can do is move it into a different ability.

**Comment by MrXofar** [comment]
Getting late for me though, so I will ponder this in my sleep and take a look at it tomorrow. :)

**Comment by SabreRunner** [comment]
Your suggestion is a good implementation. I'm excited for this.

**Comment by MrXofar** [comment]
I'm thinking something like this. 
As you scroll (with mouse wheel) left or right, the values that land in the three center blocks are totaled in the center block below - which can be dragged onto the abilities; and those d6 results are removed from the list.

![image](https://user-images.githubusercontent.com/103948142/180671871-0cd65df4-61c4-4e16-b3e2-7a04d929bbb6.png)

The result list wraps infinitely. Initially, not all results are visible simultaneously. I could change that, but where larger numbers of dice are rolled (24+) it will appear less appealing as blocks become too small, I think.

**Comment by SabreRunner** [comment]
That'll be very cool. :)

**Comment by MrXofar** [comment]
Looking good so far.
I am putting the total on same line as "ring". I may or may not hide empty blocks when they occur. (This roll sucks lol - this guy is getting stuck with a 3 somewhere) 
![image](https://user-images.githubusercontent.com/103948142/181054826-efbd53ce-4bbc-4530-8e6d-a2e173124a60.png)
I may fiddle around with more layout ideas.

**Comment by MrXofar** [comment]
It's difficult to squeeze so many digits in there. This is 21d6
![image](https://user-images.githubusercontent.com/103948142/181133034-ee763a0c-65bf-4032-8bf0-0e6540fe959c.png)

**Comment by MrXofar** [comment]
I could go wider on the window I suppose

**Comment by MrXofar** [comment]
I think this is the final layout I am going to settle on. The die rolls will fit fine now with my better use of flex css - 27 rolls shown here. I removed the "extra" blocks as they were pretty useless since I am displaying all results anyway - plus having the note there will be handy for anyone who has never seen this method. Need to do more regression testing and then I will release. Thanks for the great idea!

![image](https://user-images.githubusercontent.com/103948142/181243191-13ccdbb8-f9c1-412f-9cd5-6b05df88a854.png)

**Comment by MrXofar** [comment]
Implemented in v3.1.0
