### ISSUE TITLE
Advanced Roleplaying System ( OSRIC ) Support?

### ISSUE THREAD

**Issue by mazirian** [MrXofar/roll-new-character-stats#8]
Would it be possible to get support for this system?
https://foundryvtt.com/packages/osric
https://gitlab.com/foundryprojects/systems/osric

**Comment by MrXofar** [comment]
Straight adding it to the supported systems makes it available and rolls work, but the Configure Actor button is not displaying even when choosing to show the button via settings. I will have to do some tweaking it seems; but yes, I can add this system.

**Comment by MrXofar** [comment]
Disregard the Configure Actor button issue. It was my own fail-safe I implemented to make sure the system was supported before making it possible to create an actor.

**Comment by MrXofar** [comment]
I have this ready to go with one exception. I am running into a pesky error message when clicking the Configure Actor button on the chat card - but it does not seem to prevent the mod from functioning. I can't seem to trap where it is coming from. 
![image](https://user-images.githubusercontent.com/103948142/214437150-cda9661f-282f-4975-a695-a430ec490d72.png)
Possibly coming from the game system itself and not Foundry. I will have to consult with "osric" system to remedy.

**Comment by MrXofar** [comment]
Error message is from "osric" system. I submitted an Issue and will provide instructions on how to correct locally for those who are comfortable with coding in general. Will be releasing update sometime today. Probably after 5pm EST.

**Comment by MrXofar** [comment]
- Implemented basic support for Advanced Roleplaying System "osric".

- KNOWN ISSUE: Advanced Roleplaying System "osric" will experience an error message that reads "Unable to find originating chat cards token/actor. [undefined/undefined]" when clicking the Configure Actor button. This message has no effect on the functionality of the mod, and is the result of a message from "osric" when a button is clicked on the chat card due to the system expecting an actor or token. No current actor or selected token is required for for RNCS chat card button to function.

I submitted an Issue to the developers but you can fix locally (if you are comfortable with coding in general) by commenting out the error message on chat.js.chatAction(event) and wrap everything that follows "if (!sourceActor) {...}" in an else{}.

Like so...
if (!sourceActor) {
     //ui.notifications.error(`Unable to find originating chat cards token/actor. [${sourceTokenId}/${sourceActorId}]`)
     return;
}
else{
     //sourceAction stuff...
}

**Comment by MrXofar** [comment]
Sorry, forgot to update this issue. Advanced Roleplaying System is now supported, and the error will no longer appear when clicking Configure Actor. Closing as resolved.
